---
title: "BIO260 Final Project"
author: "HoJin Shin, Qianyu Yuan, Yi Wang"
date: "2016년 4월 24일"
output: html_document
---

---
title: "BIO260 Final Project"
author: "HoJin Shin, Qianyu Yuan, Yi Wang"
date: "2016년 4월 24일"
output: html_document
---

## Project Overview


### Motivation

Yelp.com which publishes crowd-sourced reviews and ratings about local restaurants is used by people as a reference to choose restaurants to go. Sometimes, however, people may be misled by the ratings since ratings may not only be influenced by quality of food, but also by other factors such as, but not limited to, service, price, location and atmosphere. In addition, researches show that weather affects mood and cognitive performance, and demographic characteristics of a city are associated with consumption patterns. Since these exogenous factors are also likely to affect customers ratings, we aim to investigate whether the ratings of restaurants can be predicted not only based on characteristics of restaurants, but also the exogenous factors.


### Objectives

Project goals: We are concerned that the current reviews in Yelps are influenced by the characteristics of its geographic, demographic background, as well as by the features of the restaurant (e.g. price, service etc.). Our goals are 1) using statistical tools to quantify the effect of geographic and demographic factors on review ratings, such as population diversity and income; 2) to quantify the effect of time varying factors such as days of week, weather and season on review ratings; 3) to give more robust recommendations (i.e adjusted ratings) for consumers based on present ratings and given conditions; 4) to assess the relationship between ratings and comments in reviews.

Optional features: Our main analysis is based on ratings of the restaurants. However, we also hypothesize that rating criteria varies among individuals and there are inconsistency between ratings and comments. As a result, we would also like to consider adjusting the actual ratings by the contents of comments using machine learning, thus giving a more robust rating.

Learning objectives: We would like to apply data wrangling, regression models, machine learning and prediction to real-life questions.


### Approach

This will detail your steps in developing your solution, including how you collected the data, alternative solutions you tried, describing statistical methods you used, and the insights you got. Equally important to your final results is how you got there! Your RMarkdown and HTML files are the place you describe and document the space of possibilities you explored at each step of your project. We strongly advise you to include many visualizations.


### Related Work
Anything that inspired you, such as a paper, a web site, or something we discussed in class.


### Initial Questions
What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?


### Data
Source, scraping method, cleanup, etc.

1.We will use the dataset from Yelp.com, including numbers of restaurants from 6 cities in the USA, Pittsburgh, Charlotte, Urbana-Champaign, Phoenix, Las Vegas and Madison. 
2.We will also use 2010 US Census Data to obtain demographic data of those cities. 
3.Weather data will be collected from the United States Historical Climatology Network (USHCN) which contains national- and regional-scale temperature changes in the contiguous regions in the USA. 


### Exploratory Analysis
What visualizations did you use to look at your data in different ways? What are the different statistical methods you considered? Justify the decisions you made, and show any major changes to your ideas. How did you reach these conclusions?

1.Modeling rating by time invariant variable: using ordered logistic regression/linear regression to study the effect of endogenous factors (e.g. category, price, service, location) and exogenous factors (e.g. population diversity, density, income and education level) on each restaurant’s rating in six cities of USA.

2.Modeling ratings by time-varying variable: using ordered logistic regression/linear regression to study the effect of days of the week, weather and season on the mean restaurant ratings.

3.Measuring model performance: we will measure discrimination (ROC) and the calibration (goodness-of fit test) for the model accuracy. Cross validation will be applied to determine an honest appraisal of the model’s performance and avoid overfitting.

Ratings v.s. comments analysis: we will use naive Bayes classifiers to quantify the preference implied in comments and analyze the association between ratings and comments.


### Final Analysis
What did you learn about the data? How did you answer the questions? How can you justify your answers?