---
title: "Adding demographic ang weather data"
output: html_document
---

```{r}
restaurant<-read.csv("restaurant.csv")
population_zip<-read.csv("population_zipcode_2009-2014.csv")
income_zip<-read.csv("income_zipcode_2009-2014.csv")
education_zip<-read.csv("education_zipcode_2009-2014.csv")
age_zip<-read.csv("age_zipcode_2009-2014.csv")
race_zip<-read.csv("race_zipcode_2009-2014.csv")
```


```{r}
##population of each zip code
library("dplyr")
population_zipdata<-population_zip%>%select(GEO.id2,HD01_VD01)
colnames(population_zipdata)<-c("zip","population_zip")
population_zipdata<-population_zipdata[-1,]

##median income of each zip code
income_zipdata<-income_zip%>%select(GEO.id2,HD01_VD02)
colnames(income_zipdata)<-c("zip","income_zip")
income_zipdata<-income_zipdata[-1,]

##bachelors degree of each zip code
education_zipdata<-education_zip%>%select(GEO.id2,HD01_VD06,HD01_VD07)
colnames(education_zipdata)<-c("zip","bachelor","graduate")
education_zipdata<-education_zipdata[-1,]

##median age of each zip code
age_zipdata<-age_zip%>%select(GEO.id2,HD01_VD02)
colnames(age_zipdata)<-c("zip","age_zip")
age_zipdata<-age_zipdata[-1,]

##combine restaurant and zipcode scale demographic data
restaurant$zip <- as.factor(as.character(restaurant$zip ))
restaurant<-restaurant[,-1]
combine<-left_join(restaurant,population_zipdata,by="zip")
combine<-left_join(combine,income_zipdata,by="zip")
combine<-left_join(combine,education_zipdata,by="zip")
combine<-left_join(combine,age_zipdata,by="zip")
combine$population_zip <- as.numeric(as.character(combine$population_zip  ))
combine$income_zip <- as.numeric(as.character(combine$income_zip  ))
combine$education_zip <- as.numeric(as.character(combine$education_zip ))
combine$age_zip <- as.numeric(as.character(combine$age_zip ))
combine<-combine%>%mutate(edu_bachelor_zip=education_zip/population_zip)
combine<-combine%>%filter(!is.na(population_zip)&!is.na(income_zip)&!is.na(education_zip)&!is.na(age_zip))
data.frame(n.na=sapply(combine, function(x)sum(is.na(x)))) 

write.csv(combine,file="combine.csv")
```


## Weather dataset cleaning

```{r}
library(dplyr)
library(readr)
library(data.table)
library(tidyr)
## Pittsburgh, PA: US420116
## Charlotte, NC: US370005
## Urbana Champaign, IL: US170004
## Phoenix, AZ: US040011
## SCOTTSDALE, TEMPE, MESA, Chandler, Gilbert, Glendale, AZ
## Las Vegas, NV: US320004 
## Medison, WI: US550006
## Mesa, AZ: US040008
## Henderson, NV: US480030
## Finding stations: http://www.ncdc.noaa.gov/cdo-web/datatools/findstation
```

### Pittsburgh
```{r}
## Read the dataset
pittsburgh <- fread("C:/Users/Hojin/Documents/BIO260/Final_project/Datasets/Weather dataset/723773_Pittsburgh.csv", na.strings=c("NA","N/A","null",-9999))

## Checking how many daily records each station has
num_rec_per_station_pitt <- pittsburgh %>% 
  group_by(STATION) %>%
  summarize(count = n()) 
  
## Pick a station which have complete data_PITTSBURGH INTERNATIONAL AIRPORT PA US
pittsburgh <- pittsburgh %>% filter(STATION == "GHCND:USW00094823") %>% select(STATION:SNOW,TMAX:WT19)
## Pick two stations, one with complete data and the other one with almost complete data
## PITTSBURGH INTERNATIONAL AIRPORT PA US & PITTSBURGH ALLEGHENY CO AIRPORT PA US
test3 <- pittsburgh %>% filter(STATION == "GHCND:USW00094823" | STATION == "GHCND:USW00014762") %>% select(STATION:SNOW,TMAX:WT19)
splitted <- t(sapply(test3$DATE, function(x) substring(x, first=c(1,5,7), last=c(4,6,8))))
test3 <- cbind(test3, splitted)
names(test3)[names(test3)=="1"] <- "yyyy"
names(test3)[names(test3)=="2"] <- "mm"
names(test3)[names(test3)=="3"] <- "dd"

test3 %>% filter(yyyy==2004 & mm == 12) %>% select(STATION:TMIN) %>%
  group_by(STATION) %>%
  summarize(mean = mean(as.numeric(TMAX)))
```

### Charlotte
```{r}
charlotte1 <- fread("C:/Users/Hojin/Documents/BIO260/Final_project/Datasets/Weather dataset/723770_Charlotte1.csv", na.strings=c("NA","N/A","null",-9999))
charlotte2 <- fread("C:/Users/Hojin/Documents/BIO260/Final_project/Datasets/Weather dataset/723771_Charlotte2.csv", na.strings=c("NA","N/A","null",-9999))
charlotte <- bind_rows(charlotte1, charlotte2)
num_rec_per_station_char <- charlotte %>% 
  group_by(STATION) %>%
  summarize(count = n()) 

## Chose the station at CHARLOTTE DOUGLAS AIRPORT NC US.
charlotte <- charlotte %>% filter(STATION == "GHCND:USW00013881") %>% select(STATION:SNOW,TMAX:WT19)
```

### Urbana_Champaign
```{r}
urbana_champaign <- fread("C:/Users/Hojin/Documents/BIO260/Final_project/Datasets/Weather dataset/723775_Champaign.csv", na.strings=c("NA","N/A","null",-9999))
num_rec_per_station_urcham <- urbana_champaign %>% 
  group_by(STATION) %>%
  summarize(count = n()) 
urbana_champaign <- urbana_champaign %>% filter(STATION == "GHCND:USC00118740") %>% select(STATION:SNOW,TMAX:WT10)
```

### Las_vegas
```{r}
las_vegas <- fread("C:/Users/Hojin/Documents/BIO260/Final_project/Datasets/Weather dataset/722987_las vegas.csv", na.strings=c("NA","N/A","null",-9999))
num_rec_per_station_lasvegas <- las_vegas %>% 
  group_by(STATION) %>%
  summarize(count = n()) 
las_vegas <- las_vegas %>% filter(STATION == "GHCND:USW00023169") %>% select(STATION:SNOW,TMAX:WV03)
```

### Henderson
```{r}
## Henderson data was included in Las Vegas'. However, most data were not available, and we decided to use the Las Vegas' weather data for this city.
henderson <- las_vegas %>% filter(STATION == "GHCND:US1NVCK0034" | STATION == "GHCND:US1NVCK0029" | STATION == "GHCND:US1NVCK0001" | STATION == "GHCND:US1NVCK0026" | STATION == "GHCND:US1NVCK0037") %>% select(STATION:SNOW,TMAX:WV03)
```

### Madison
```{r}
madison <- fread("C:/Users/Hojin/Documents/BIO260/Final_project/Datasets/Weather dataset/722991_madison.csv", na.strings=c("NA","N/A","null",-9999))
num_rec_per_station_madison <- madison %>% 
  group_by(STATION) %>%
  summarize(count = n()) 
madison <- madison %>% filter(STATION == "GHCND:USW00014837") %>% select(STATION:SNOW,TMAX:WT19)
```

### Phoenix, Scottsdale, Tempe, Mesa, Chandler, Gilbert, Glendale
```{r}
phoenix1 <- fread("C:/Users/Hojin/Documents/BIO260/Final_project/Datasets/Weather dataset/723777_Phoenix1.csv", na.strings=c("NA","N/A","null",-9999))
phoenix2 <- fread("C:/Users/Hojin/Documents/BIO260/Final_project/Datasets/Weather dataset/723779_Phoenix2.csv", na.strings=c("NA","N/A","null",-9999))
phoenix <- bind_rows(phoenix1, phoenix2)
num_rec_per_station_phoenix <- phoenix %>% 
  group_by(STATION) %>%
  summarize(count = n()) 

## Chose the station at PHOENIX SKY HARBOR INTERNATIONAL AIRPORT AZ US
az <- phoenix %>% filter(STATION == "GHCND:USW00023183") %>% select(STATION:SNOW,TMAX:WT03)
```

### Joining datasets
```{r}
weather <- pittsburgh %>% union(madison) %>% union(charlotte) %>% mutate(WV03 = NA)
weather$WV03 <- as.integer(weather$WV03) 
                                                                         
las_vegas <- las_vegas %>% mutate(WT22 = NA, WT17 = NA, WT19 = NA, WT21 = NA, WT15 = NA)
las_vegas$WT22 <- as.integer(las_vegas$WT22) 
las_vegas$WT17 <- as.integer(las_vegas$WT17) 
las_vegas$WT19 <- as.integer(las_vegas$WT19) 
las_vegas$WT21 <- as.integer(las_vegas$WT21) 
las_vegas$WT15 <- as.integer(las_vegas$WT15)

weather <- weather %>% union(las_vegas)

az <- az %>% mutate(WT09 = NA, WT22 = NA, WT17 = NA, WT19 = NA, WV03 = NA, WT15 = NA) 
az$WT09 <- as.integer(az$WT09) 
az$WT22 <- as.integer(az$WT22) 
az$WT17 <- as.integer(az$WT17) 
az$WT19 <- as.integer(az$WT19) 
az$WV03 <- as.integer(az$WV03) 
az$WT15 <- as.integer(az$WT15)

weather <- weather %>% union(az) %>% mutate(WT10 = NA)
weather$WT10 <- as.integer(weather$WT10)

urbana_champaign <- urbana_champaign %>% mutate(WT18 = NA, WT16 = NA, WT22 = NA, WT17 = NA, WT07 = NA, WT14 = NA, WT19 = NA, WT13 = NA, WT21 = NA, WV03 = NA, WT15 = NA) 
urbana_champaign$WT18 <- as.integer(urbana_champaign$WT18) 
urbana_champaign$WT16 <- as.integer(urbana_champaign$WT16)
urbana_champaign$WT22 <- as.integer(urbana_champaign$WT22)
urbana_champaign$WT17 <- as.integer(urbana_champaign$WT17)
urbana_champaign$WT07 <- as.integer(urbana_champaign$WT07)
urbana_champaign$WT14 <- as.integer(urbana_champaign$WT14)
urbana_champaign$WT19 <- as.integer(urbana_champaign$WT19)
urbana_champaign$WT13 <- as.integer(urbana_champaign$WT13)
urbana_champaign$WT21 <- as.integer(urbana_champaign$WT21)
urbana_champaign$WV03 <- as.integer(urbana_champaign$WV03)
urbana_champaign$WT15 <- as.integer(urbana_champaign$WT15)

weather <- weather %>% union(urbana_champaign)
```

```{r}
splitted <- t(sapply(weather$DATE, function(x) substring(x, first=c(1,5,7), last=c(4,6,8))))
weather <- cbind(weather, splitted) %>% select(STATION:DATE,V1:V3,PRCP:WT10)
library(plyr)
weather <- rename(weather, c("V1"="yyyy", "V2"="mm", "V3" = "dd"))
detach(package:plyr)

library(lubridate)
weather_original <- weather %>% unite(DATE_NEW, yyyy, mm, dd) %>% 
        mutate(DATE_NEW = ymd(DATE_NEW)) %>%
        select(STATION:STATION_NAME,DATE_NEW:WT10)
detach(package:lubridate)
names(weather_original)[names(weather_original)=="DATE_NEW"] <- "DATE"
rm(splitted, weather)

## Date range from 2005-02-01 to 2015-12-24 
weather <- weather_original %>% filter(DATE>="2005-02-01" & DATE<="2015-12-24") %>% arrange(DATE)

write.csv(weather, file="C:/Users/Hojin/Documents/BIO260/Final_project/Datasets/weather_clean.csv", row.names=FALSE)
```