---
title: "Adding demographic ang weather data"
output: html_document
---

```{r}
restaurant<-read.csv("restaurant.csv")
population_zip<-read.csv("population_zipcode_2009-2014.csv")
income_zip<-read.csv("income_zipcode_2009-2014.csv")
education_zip<-read.csv("education_zipcode_2009-2014.csv")
age_zip<-read.csv("age_zipcode_2009-2014.csv")
race_zip<-read.csv("race_zipcode_2009-2014.csv")
```


```{r}
##population of each zip code
library("dplyr")
population_zipdata<-population_zip%>%select(GEO.id2,HD01_VD01)
colnames(population_zipdata)<-c("zip","population_zip")
population_zipdata<-population_zipdata[-1,]

##median income of each zip code
income_zipdata<-income_zip%>%select(GEO.id2,HD01_VD02)
colnames(income_zipdata)<-c("zip","income_zip")
income_zipdata<-income_zipdata[-1,]

##bachelors degree of each zip code
education_zipdata<-education_zip%>%select(GEO.id2,HD01_VD06)
colnames(education_zipdata)<-c("zip","education_zip")
education_zipdata<-education_zipdata[-1,]

##median age of each zip code
age_zipdata<-age_zip%>%select(GEO.id2,HD01_VD02)
colnames(age_zipdata)<-c("zip","age_zip")
age_zipdata<-age_zipdata[-1,]

##combine restaurant and zipcode scale demographic data
restaurant$zip <- as.factor(as.character(restaurant$zip ))
combine<-left_join(restaurant,population_zipdata,by="zip")
combine<-left_join(combine,income_zipdata,by="zip")
combine<-left_join(combine,education_zipdata,by="zip")
combine<-left_join(combine,age_zipdata,by="zip")
```


